services:
  capstone-mysql:
    image: mysql:latest
    container_name: capstone
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234!
      MYSQL_DATABASE: capstone
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"

  capstone_redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"

  capstone_redis_test:
    image: redis:latest
    container_name: redis_test
    ports:
      - "6381:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - ./prometheus/data:/prometheus
#    networks:
#      - monitor

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_INSTALL_PLUGINS=redis-datasource
    restart: always
    ports:
      - 3000:3000

  redis-exporter:
    container_name: redis-exporter
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - 9121:9121
    depends_on:
      - prometheus
#    networks:
#      - monitor
    restart: always
