services:
  mysql:
    image: mysql:latest
    container_name: capstone
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234!
      MYSQL_DATABASE: capstone
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"

