services:
  capstone-mysql:
    image: mysql:latest
    container_name: capstone
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234!
      MYSQL_DATABASE: capstone
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"

  capstone_redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"

  capstone_redis_test:
    image: redis:latest
    container_name: redis_test
    ports:
      - "6381:6379"


  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_INSTALL_PLUGINS=redis-datasource
    restart: always
    ports:
      - 3000:3000

