server:
  port: ${SERVER_PORT:8080}
spring:
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:/yaml/application-local.yaml
      - classpath:/yaml/application-dev.yaml
  profiles:
    active: local
