spring.config.activate.on-profile: dev

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    defer-datasource-initialization: false
  data:
    redis:
      port: ${REDIS_PORT}
logging:
  level:
    org.hibernate.SQL: trace
